### PR TITLE
Add tryGetWindowAttributes.

### PR DESCRIPTION
**Pull request by kurnevsky**
As discussed here https://github.com/xmonad/xmonad-contrib/pull/17

### CODE REVIEW

**Comment by dmwit** [comment]
Can we get away with just adding a `throwIfZero` call to `getWindowAttributes` instead?

**Comment by kurnevsky** [comment]
@dmwit Do you suggest to catch the exception?

**Comment by dmwit** [comment]
That is exactly what I suggest, yes.

**Comment by dmwit** [comment]
I've made my proposed change instead with commit 9d74fd2.

**Comment by asjo** [comment]
@dmwit Didn't you already merge an almost identical change? https://github.com/xmonad/X11/commit/feaf03e2e4bff4b041e794e4ef3b654bbcb278c2

Note that XMonad needs some changes to not crash when getWindowAttributes throws an exception on error, see https://github.com/xmonad/xmonad/pull/9 which contains my attempts at handling the two I have hit.

**Comment by dmwit** [comment]
Oops, my local repo was in the optional-xrandr branch when I committed 9d74fd2. Since your modifications already add the call to `throwIfZero`, I see no reason to port that commit to master. Just another annoyance to deal with if we ever have to merge in optional-xrandr.

Seeing that change in two commits and yet only seeing the result of one of them was quite confusing until I realized!

Anyway, consider this pull request now doubly closed.

**Comment by asjo** [comment]
Ah, I didn't notice that either!

**Pull request closed without merging**
