### PR TITLE
Add missing FocusChangeEvent

### PR DESCRIPTION
**Pull request by scolej**
Hi, this PR adds the FocusChangeEvent which seems to be missing.

### CODE REVIEW

**Review by slotThe — APPROVED** [review]
LGTM

**Comment by slotThe** [comment]
@geekosaur @liskin what do you people think?

**Comment by geekosaur** [comment]
I think we may be missing a few others as well, and had always wondered why. I'm fine with it.

**Comment by slotThe** [comment]
Cool, thanks!

**Comment by scolej** [comment]
Thank you both. I'll keep an eye out for other missing items...

**Comment by liskin** [comment]
@scolej Shall we cut a release (we'll still need a changelog entry for this PR) now or do you intend to add more missing stuff soon?

**Comment by scolej** [comment]
Hoping to add some more stuff:
- createnotify event
- some missing constants in `Types.hsc`

**Comment by liskin** [comment]
With #82 now merged, time to do a release? :-)
(Still needs an entry in CHANGES.md)

**Pull request merged**
